name: Build Nuxt Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Nuxt Project
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Install project dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build the Nuxt project
      - name: Build Nuxt project
        run: pnpm run build
