name: Cypress and Chromatic Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  # Cypress Test Job
  run-cypress:
    name: Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Start the Nuxt server
        run: pnpm run dev &
      
      - name: Wait for Nuxt server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: pnpm cypress

  # Chromatic Visual Regression Job (depends on Cypress test)
  run-chromatic:
    name: Chromatic Visual Regression
    runs-on: ubuntu-latest
    needs: run-cypress

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Publish to Chromatic
        run: pnpm run chromatic -- --auto-accept-changes
